version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: on-failure  
    volumes: 
      - /app/node_modules
      - .:/app # dot is for current directory
  tests: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules # to nod override it
      - .:/app 
    # override starting command for tests
    command: ["npm", "run", "test"] 